name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

  AWS_REGION: ap-south-1

  TF_VAR_hub_vpc_cidr: ${{ vars.HUB_VPC_CIDR }}
  TF_VAR_transit_gateway_id: ${{ vars.TRANSIT_GATEWAY_ID }}
  TF_VAR_hub_test_ip: ${{ vars.HUB_TEST_IP }}

jobs:

  terraform-apply:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/prod

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::434097521299:role/EC2-SSM-Spoke-Role
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt 

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Verify GitHub Variables
        shell: bash
        run: |
          set -e

          echo "Checking GitHub Actions variables..."

          if [ -z "${{ vars.HUB_VPC_CIDR }}" ]; then
            echo "ERROR: GitHub variable HUB_VPC_CIDR is missing."
            echo "Go to Settings -> Secrets and variables -> Actions -> Variables."
            exit 1
          fi

          if [ -z "${{ vars.TRANSIT_GATEWAY_ID }}" ]; then
            echo "ERROR: GitHub variable TRANSIT_GATEWAY_ID is missing."
            exit 1
          fi

          if [ -z "${{ vars.HUB_TEST_IP }}" ]; then
            echo "ERROR: GitHub variable HUB_TEST_IP is missing."
            exit 1
          fi

          echo "HUB_VPC_CIDR: configured"
          echo "TRANSIT_GATEWAY_ID: configured"
          echo "HUB_TEST_IP: configured"

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="hub_test_port=80" \
            -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
